In [1]:
import numpy as np
import scipy as sp
from scipy.optimize import leastsq
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
x = np.linspace(0, 1, 200)

In [3]:
x

array([0.        , 0.00502513, 0.01005025, 0.01507538, 0.0201005 ,
       0.02512563, 0.03015075, 0.03517588, 0.04020101, 0.04522613,
       0.05025126, 0.05527638, 0.06030151, 0.06532663, 0.07035176,
       0.07537688, 0.08040201, 0.08542714, 0.09045226, 0.09547739,
       0.10050251, 0.10552764, 0.11055276, 0.11557789, 0.12060302,
       0.12562814, 0.13065327, 0.13567839, 0.14070352, 0.14572864,
       0.15075377, 0.15577889, 0.16080402, 0.16582915, 0.17085427,
       0.1758794 , 0.18090452, 0.18592965, 0.19095477, 0.1959799 ,
       0.20100503, 0.20603015, 0.21105528, 0.2160804 , 0.22110553,
       0.22613065, 0.23115578, 0.2361809 , 0.24120603, 0.24623116,
       0.25125628, 0.25628141, 0.26130653, 0.26633166, 0.27135678,
       0.27638191, 0.28140704, 0.28643216, 0.29145729, 0.29648241,
       0.30150754, 0.30653266, 0.31155779, 0.31658291, 0.32160804,
       0.32663317, 0.33165829, 0.33668342, 0.34170854, 0.34673367,
       0.35175879, 0.35678392, 0.36180905, 0.36683417, 0.37185

In [4]:
p_init = np.random.rand(0 + 1)

In [5]:
p_init

array([0.65007467])

In [6]:
# 目标函数𝑦=𝑠𝑖𝑛2𝜋𝑥——在几个频率值下测试：1,2,3,9
def real_func(x):
    #return np.sin(2*np.pi*x)
    #return np.sin(2*2*np.pi*x)
    return np.sin(4*2*np.pi*x)
    #return np.sin(8*2*np.pi*x)

# 多项式
def fit_func(p, x):
    f = np.poly1d(p)
    return f(x)

# 残差
def residuals_func(p, x, y):
    ret = fit_func(p, x) - y
    return ret

In [7]:
y_ = real_func(x)

In [8]:
y_

array([ 0.00000000e+00,  1.25959705e-01,  2.49912962e-01,  3.69885285e-01,
        4.83965601e-01,  5.90336692e-01,  6.87304143e-01,  7.73323331e-01,
        8.47024034e-01,  9.07232251e-01,  9.52988909e-01,  9.83565137e-01,
        9.98473878e-01,  9.97477646e-01,  9.80592311e-01,  9.48086844e-01,
        9.00479032e-01,  8.38527236e-01,  7.63218303e-01,  6.75751849e-01,
        5.77521152e-01,  4.70090958e-01,  3.55172553e-01,  2.34596503e-01,
        1.10283499e-01, -1.57862420e-02, -1.41604519e-01, -2.65167138e-01,
       -3.84505835e-01, -4.97719629e-01, -6.03005107e-01, -6.98685146e-01,
       -7.83235632e-01, -8.55309735e-01, -9.13759368e-01, -9.57653470e-01,
       -9.86292838e-01, -9.99221269e-01, -9.96232822e-01, -9.77375101e-01,
       -9.42948495e-01, -8.93501396e-01, -8.29821460e-01, -7.52923064e-01,
       -6.64031143e-01, -5.64561683e-01, -4.56099159e-01, -3.40371303e-01,
       -2.19221577e-01, -9.45798078e-02,  3.15685498e-02,  1.57214043e-01,
        2.80355229e-01,  

In [9]:
y = [np.random.normal(0, 0.2) + y1 for y1 in y_]

In [10]:
y

[-0.44625834789469554,
 0.16704453118389614,
 0.14284359787274542,
 0.5146028067335849,
 0.5295435104442836,
 0.6296284144663713,
 0.5130329733687328,
 0.45334288790499117,
 0.8448682595705242,
 0.9078089005346508,
 0.8706021211963828,
 1.3960555893143236,
 0.8427285019620299,
 0.9907858189502227,
 0.6779459251365648,
 0.9495194897253185,
 0.9305603144873688,
 1.0223824131245942,
 0.32692658153041265,
 0.6121298856186546,
 0.6220625763316151,
 0.4146794103891959,
 0.0012332513555402547,
 0.2360647791418283,
 0.07263544604316481,
 -0.08924317602815346,
 -0.02290713514661795,
 -0.38855918320130683,
 -0.714055923454708,
 -0.706142011294371,
 -0.6155630498779364,
 -0.6370014411284785,
 -1.0796517676375037,
 -0.7000525274196353,
 -0.8190731685259017,
 -1.0108844440266844,
 -0.8125507469813714,
 -1.2778517370134599,
 -1.0176904998991605,
 -1.1185569974261613,
 -0.7459669131767828,
 -0.6590842347451841,
 -0.818237345311599,
 -0.9425281486790752,
 -0.5102607114268823,
 -0.5860438855978308,
 -0

In [11]:
f = np.poly1d([1,2,3])

In [12]:
f

poly1d([1, 2, 3])

In [13]:
f(1)

6

In [14]:
f(2)

11

In [15]:
f([1,2,3])

array([ 6, 11, 18])

In [17]:
np.random.rand(3 + 1)

array([0.01363313, 0.43860007, 0.78744882, 0.32147343])